# config/meta.yml

meta_product_name: "Centree"

meta_title: "Centree – Centralizing information and providing safety"

meta_description: "A beacon of hope and guidance for migrants journeying towards a new beginning in Europe"

meta_image: "migration.png" # should exist in `app/assets/images/`

twitter_account: "@product_twitter_account" # required for Twitter Cards
